### ISSUE TITLE
Automatically start the Video capture on node startup

### ISSUE THREAD

**Issue by ladrians** [dganbold/raspicam_node#2]
Is there a way to automatically start capturing video image without calling the service?
  rosservice call /raspicam_node/start_capture
thanks,

**Comment by ladrians** [comment]
Just to let you know that I added the following at the end of the raspicam_node.cpp main method (before the ros spin one) and worked:

	start_capture(&state_srv);

It would be nice to add a property to start automatically or use current behavior? regards,

**Comment by dganbold** [comment]
If you prefer to do that without any source code modification, You can call the service from the launch file. I just added some launch files. Check it, https://github.com/dganbold/raspicam_node/tree/master/launch

**Comment by ladrians** [comment]
great thanks!
